- CHANGELOG.md
- lib/Role/RoleCreate/RoleCreate.test.js
- lib/hooks/useAuthorizationRoles/useAuthorizationRoles.js
- lib/hooks/useCreateRoleMutation/useCreateRoleMutation.js
add support for fetching roles by `tenantId` when the user selects members from the members list
https://github.com/folio-org/ui-consortia-settings/pull/129
https://github.com/folio-org/stripes-authorization-components/assets/116072773/5923b9f5-25d0-4961-b4b1-f69f381c02cd
Ideally all of the PRs involved in breaking changes would be merged in the same day …
> add support for fetching roles by tenantId

- CHANGELOG.md
- lib/hooks/useRoleCapabilities/useRoleCapabilities.js
…
[UISAUTHCOM-6](https://folio-org.atlassian.net/browse/UISAUTHCOM-6) - Capabilities related to set not unchecked when set is unchecked when editing role
Add expand parameter to queryKey in useRoleCapabilities. 
Retrieving capabilities with query param `expand` returns different results. And reusing the hook in the different components with different expand parameter returned the same cached result, since query keys are not changed. Just provide the additional queryKey to useQuery hook. 
- What other modules will these …
> UISAUTHCOM-6: add expand parameter to queryKey in useRoleCapabilities hook

- lib/Capabilities/CapabilitiesSection/CapabilitiesSection.js
- lib/Capabilities/constants.js
- lib/Capabilities/utils.js
- lib/hooks/index.js
- lib/hooks/useUserCapabilities/index.js
- lib/hooks/useUserCapabilities/useUserCapabilities.js
- lib/hooks/useUserCapabilities/useUserCapabilities.test.js
- lib/hooks/useUserCapabilitiesSets/index.js
- lib/hooks/useUserCapabilitiesSets/useUserCapabilitiesSets.js
- lib/hooks/useUserCapabilitiesSets/useUserCapabilitiesSets.test.js
- lib/utils/isUnique.js
https://folio-org.atlassian.net/browse/UISAUTHCOM-8
Here we added new hooks for fetching capabilities needed in https://folio-org.atlassian.net/browse/UICONSET-167
> UISAUTHCOM-8: Add hooks for fetching users-capabilities

- CHANGELOG.md
- lib/PolicyDetails/PolicyDetails/PolicyDetails.js
- lib/PolicyDetails/PolicyDetails/PolicyDetails.test.js
- lib/PolicyDetails/PolicyDetails/index.js
- lib/PolicyDetails/index.js
- lib/PolicyDetails/style.css
- lib/SearchForm/SearchForm.js
- lib/constants/constants.js
- lib/constants/index.js
- lib/hooks/useAuthorizationPolicies/index.js
- lib/hooks/useAuthorizationPolicies/useAuthorizationPolicies.js
- lib/hooks/useAuthorizationPolicies/useAuthorizationPolicies.test.js
- lib/hooks/useUsers/useUsers.js
- lib/index.js
- translations/stripes-authorization-components/en.json
[UISAUTHCOM-11](https://folio-org.atlassian.net/browse/UISAUTHCOM-11): Move reusable components from `ui-authorization-policies` repository.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> UISAUTHCOM-11: Move reusable components from `ui-authorization-policies` repository.

- lib/hooks/index.js
> UISAUTHCOM-11 export useAuthorizationPolicies

- lib/hooks/useAuthorizationPolicies/useAuthorizationPolicies.js
- lib/hooks/useAuthorizationPolicies/useAuthorizationPolicies.test.js
- lib/hooks/useAuthorizationRoles/useAuthorizationRoles.js
- lib/hooks/useAuthorizationRoles/useAuthorizationRoles.test.js
- lib/hooks/useRoleById/useRoleById.js
- lib/hooks/useRoleById/useRoleById.test.js
- lib/hooks/useUserGroups/useUserGroups.js
- lib/hooks/useUserGroups/useUsergroups.test.js
- lib/hooks/useUsersByRoleId/useUsersByRoleId.js
- lib/hooks/useUsersByRoleId/useUsersByRoleId.test.js
Extend hook options to support error handling and other query options - for the supporting PR https://github.com/folio-org/ui-consortia-settings/pull/142
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …
> Extend hook options to support error handling and other query options

- lib/hooks/useAuthorizationRolesMutation/useAuthorizationRolesMutation.js
- lib/hooks/useAuthorizationRolesMutation/useAuthorizationRolesMutation.test.js
- translations/stripes-authorization-components/en.json
[UISAUTHCOM-19](https://folio-org.atlassian.net/browse/UISAUTHCOM-19): update duplicate role name with current date and time
https://github.com/user-attachments/assets/97601904-f25f-4dce-b9c4-5be8cf10dda7
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
> UISAUTHCOM-19: update duplicate role name with current date and time

- CHANGELOG.md
- lib/Capabilities/CapabilitiesDataType/CapabilitiesDataType.js
- lib/Capabilities/CapabilitiesProcedural/CapabilitiesProcedural.js
- lib/Capabilities/CapabilitiesSettings/CapabilitiesSettings.js
[UISAUTHCOM-16](https://folio-org.atlassian.net/browse/UISAUTHCOM-16) - Improve capability tables navigation for authorization roles UI
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> UISAUTHCOM-16: provide maxHeight to the capabilities tables

- lib/RoleDetails/RoleDetails.js
- lib/RoleDetails/RoleDetailsGeneralInfoAccordion/RoleDetailsGeneralInfoAccordion.js
- lib/RoleDetails/RoleDetailsGeneralInfoAccordion/index.js
- lib/hooks/useRoleById/useRoleById.js
- lib/hooks/useUsers/useUsers.js
https://folio-org.atlassian.net/browse/UISAUTHCOM-14
- Move general info of the role to the separate component;
- Close a shared pane after deletion;
- Provide `tenantId` option to the `useUsers` hook;
Changelog has been already updated.
https://github.com/user-attachments/assets/6cbddc63-dc73-4225-a6f4-4a41480f6347
Ideally all of the PRs involved in …
> UISAUTHCOM-14 UX fixes for roles details

- CHANGELOG.md
- lib/RoleDetails/RoleDetailsUsersAccordion/RoleDetailsUsersAccordion.js
- lib/RoleDetails/RoleDetailsUsersAccordion/RoleDetailsUsersAccordion.test.js
[UISAUTHCOM-27](https://folio-org.atlassian.net/browse/UISAUTHCOM-27) - "Create user records in Keycloak" confirmation dialog appears prematurely 
Use Loading, ConfirmationDialog and MCL in the accordion body
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …
> UISAUTHCOM-27: fix Keycloak user confirmation dialog appears prematurely

- CHANGELOG.md
- lib/RoleDetails/RoleDetails.js
https://folio-org.atlassian.net/browse/UISAUTHCOM-29
While it's helpful for reviewers to …
> UISAUTHCOM-29 Protect mutation actions of roles by permissions

- lib/constants/api.js
- lib/constants/constants.js
- lib/hooks/index.js
- lib/hooks/useUserRolesById/index.js
- lib/hooks/useUserRolesById/useUserRolesById.js
- lib/hooks/useUserRolesById/useUserRolesById.test.js
https://folio-org.atlassian.net/browse/UISAUTHCOM-25
Here we added a new hook for fetching roles directly by single userId.
> UISAUTHCOM-25: Update user capability hooks(follow-up)

- CHANGELOG.md
- lib/RoleDetails/RoleDetails.js
- lib/hooks/consortia/useInitialRoleSharing/useInitialRoleSharing.js
> UISAUTHCOM-36 Avoid extra capability requests for role sharing when not in central tenant

- CHANGELOG.md
- lib/RoleDetails/RoleDetailsAssignUsers/RoleDetailsAssignUsers.js
- lib/RoleDetails/RoleDetailsAssignUsers/RoleDetailsAssignUsers.test.js
- translations/stripes-authorization-components/en.json
[UISAUTHCOM-37](https://folio-org.atlassian.net/browse/UISAUTHCOM-37): ECS - Add Tenant identifier to title of Select user modal
https://github.com/user-attachments/assets/758a3902-eeda-46b3-9cf4-6b2ee06fff57
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …
> UISAUTHCOM-37: ECS - Add Tenant identifier to title of Select user modal

- lib/RoleDetails/RoleDetailsAssignUsers/RoleDetailsAssignUsers.js
[UISAUTHCOM-37](https://folio-org.atlassian.net/browse/UISAUTHCOM-37): hide tenant name if `tenantId` is missing (Follow up)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> UISAUTHCOM-37: hide tenant name if `tenantId` is missing (Follow up)

- lib/Role/RoleCreate/RoleCreate.js
> UISAUTHCOM-43-followup:  apply changed signature for useApplicationCapabilitySets in RoleCreate

- CHANGELOG.md
- lib/Capabilities/CapabilitiesAccordion/CapabilitiesAccordion.test.js
- lib/Capabilities/CapabilitiesGrid/CapabilitiesGrid.js
- lib/Capabilities/CapabilitiesSection/CapabilitiesSection.test.js
- lib/Capabilities/CapabilitiesSetsAccordion/CapabilitiesSetsAccordion.test.js
- lib/Capabilities/constants.js
- lib/Policy/PolicyFormContainer/PolicyFormContainer.test.js
- lib/PolicyDetails/PolicyDetails/PolicyDetails.test.js
- lib/Role/RoleCreate/RoleCreate.test.js
- lib/Role/RoleEdit/RoleEdit.test.js
- lib/RoleDetails/RoleDetails.test.js
- lib/SearchForm/SearchForm.test.js
- package.json
- translations/stripes-authorization-components/en.json
Add accessibility tests with deque axe.
Refs [UISAUTHCOM-44](https://folio-org.atlassian.net/browse/UISAUTHCOM-44)
> UISAUTHCOM-44 add deque axe a11y tests

- CHANGELOG.md
- lib/hooks/useAuthorizationRolesMutation/useAuthorizationRolesMutation.js
- lib/hooks/useAuthorizationRolesMutation/useAuthorizationRolesMutation.test.js
> UISAUTHCOM-49 put regular role type when duplicating

- CHANGELOG.md
- lib/hooks/useApplicationCapabilitySets/useApplicationCapabilitySets.js
Refs [UISAUTHCOM-48](https://folio-org.atlassian.net/browse/UISAUTHCOM-48).
updated line code of useApplicationCapabilitySets accidentally got into the release. Revert the line back 
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
> UISAUTHCOM-48: fix cap set remains assigned after selecting and then deselecting it when creating an authorization role

- CHANGELOG.md
- package.json
Refs [UISAUTHCOM-50](https://folio-org.atlassian.net/browse/UISAUTHCOM-50) - migrate stripes dependencies to their Sunflower versions.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> UISAUTHCOM-50: *Breaking* migrate stripes dependencies to their Sunflower versions.

- CHANGELOG.md
Putting work items in correct release and adding tag links.
> Update CHANGELOG with 2.0.1 release

- package.json
> bump version to 2.0.1
